### ISSUE TITLE
프로젝트 관리 도구를 사용하지 않는 유저들을 위한 가이드 제공

### ISSUE THREAD

**Issue by shin285** [komoran/docs#1]
gradle이나 maven과 같은 프로젝트 관리 도구를 사용하지 않는 유저들을 위한 가이드 제공

**Comment by 9bow** [comment]
@shin285 
`git clone` 또는 소스코드 다운로드 후 jar를 빌드하는 것부터 시작하려고 합니다.
(다만, 이후 release부터는 jar 파일도 포함해주시면 단계가 많이 단축될 것 같습니다.)

**Comment by shin285** [comment]
네~ 이 부분은 제가 그 문서 편집하는 방법도 익힐겸 직접해볼게요~

**Comment by 9bow** [comment]
"[Gradle/Maven 없이 형태소 분석 따라하기](https://docs.komoran.kr/firststep/tutorial-java.html)" 문서를 추가하였습니다.
